<?php
/**
* Generated by the WordPress Option Page generator
* at http://jeremyhixon.com/wp-tools/option-page/
*/

class PointsAPI {
private $points_api_options;

public function __construct() {
add_action( 'admin_menu', array( $this, 'points_api_add_plugin_page' ) );
add_action( 'admin_init', array( $this, 'points_api_page_init' ) );
}

public function points_api_add_plugin_page() {
add_menu_page(
'Points API', // page_title
'Points API', // menu_title
'manage_options', // capability
'points-api', // menu_slug
array( $this, 'points_api_create_admin_page' ), // function
'dashicons-admin-generic', // icon_url
100 // position
);
}

public function points_api_create_admin_page() {
$this->points_api_options = get_option( 'points_api_settings' ); ?>

<div class="wrap">
	<h2>Points API</h2>
	<p>Points API Settings</p>
	<?php settings_errors(); ?>

	<form method="post" action="options.php">
		<?php
		settings_fields( 'points_api_option_group' );
		do_settings_sections( 'points-api-admin' );
		submit_button();
		?>
	</form>
</div>
<?php }

public function points_api_page_init() {
	register_setting(
		'points_api_option_group', // option_group
		'points_api_settings', // option_name
		array( $this, 'points_api_sanitize' ) // sanitize_callback
	);

	add_settings_section(
		'points_api_setting_section', // id
		'Settings', // title
		array( $this, 'points_api_section_info' ), // callback
		'points-api-admin' // page
	);

	add_settings_field(
		'points_api_enabled', // id
		'Points API Enabled', // title
		array( $this, 'points_api_enabled_callback' ), // callback
		'points-api-admin', // page
		'points_api_setting_section' // section
	);

	add_settings_field(
		'signup_url', // id
		'Signup URL', // title
		array( $this, 'signup_url_callback' ), // callback
		'points-api-admin', // page
		'points_api_setting_section' // section
	);

	add_settings_field(
		'login_url', // id
		'Login URL', // title
		array( $this, 'login_url_callback' ), // callback
		'points-api-admin', // page
		'points_api_setting_section' // section
	);

	add_settings_field(
		'fetch_user_data_url', // id
		'Fetch User-data URL', // title
		array( $this, 'fetch_user_data_url_callback' ), // callback
		'points-api-admin', // page
		'points_api_setting_section' // section
	);
}

public function points_api_sanitize($input) {
	$sanitary_values = array();
	if ( isset( $input['points_api_enabled'] ) ) {
		$sanitary_values['points_api_enabled'] = $input['points_api_enabled'];
	}

	if ( isset( $input['signup_url'] ) ) {
		$sanitary_values['signup_url'] = sanitize_text_field( $input['signup_url'] );
	}

	if ( isset( $input['login_url'] ) ) {
		$sanitary_values['login_url'] = sanitize_text_field( $input['login_url'] );
	}

	if ( isset( $input['fetch_user_data_url'] ) ) {
		$sanitary_values['fetch_user_data_url'] = sanitize_text_field( $input['fetch_user_data_url'] );
	}

	return $sanitary_values;
}

public function points_api_section_info() {

}

public function points_api_enabled_callback() {
	printf(
		'<input type="checkbox" name="points_api_settings[points_api_enabled]" id="points_api_enabled" value="points_api_enabled" %s> <label for="points_api_enabled">Check this to use Points API plugin features</label>',
		( isset( $this->points_api_options['points_api_enabled'] ) && $this->points_api_options['points_api_enabled'] === 'points_api_enabled' ) ? 'checked' : ''
	);
}

public function signup_url_callback() {
	printf(
		'<input class="regular-text" type="text" name="points_api_settings[signup_url]" id="signup_url" value="%s">',
		isset( $this->points_api_options['signup_url'] ) ? esc_attr( $this->points_api_options['signup_url']) : ''
	);
}

public function login_url_callback() {
	printf(
		'<input class="regular-text" type="text" name="points_api_settings[login_url]" id="login_url" value="%s">',
		isset( $this->points_api_options['login_url'] ) ? esc_attr( $this->points_api_options['login_url']) : ''
	);
}

public function fetch_user_data_url_callback() {
	printf(
		'<input class="regular-text" type="text" name="points_api_settings[fetch_user_data_url]" id="fetch_user_data_url" value="%s">',
		isset( $this->points_api_options['fetch_user_data_url'] ) ? esc_attr( $this->points_api_options['fetch_user_data_url']) : ''
	);
}

}
if ( is_admin() )
	$points_api = new PointsAPI();

/*
 * Retrieve this value with:
 * $points_api_options = get_option( 'points_api_settings' ); // Array of All Options
 * $points_api_enabled = $points_api_options['points_api_enabled']; // Points API Enabled
 * $signup_url = $points_api_options['signup_url']; // Signup URL
 * $login_url = $points_api_options['login_url']; // Login URL
 * $fetch_user_data_url = $points_api_options['fetch_user_data_url']; // Fetch User-data URL
 */
